[package]
name = "PikminPilotPairingHelper"
version = "0.1.2"
edition = "2024"
rust-version = "1.92"

[dependencies]
idevice = { version = "=0.1.61", features = [
  "pair",
  "core_device_proxy",
  "remote_pairing",
  "rsd",
  "tunnel_tcp_stack",
  "usbmuxd",
] }
tokio = { version = "1.53", features = ["rt-multi-thread", "macros", "net", "time"] }
