[package]
name = "PikminPilotPairingHelper"
version = "0.1.0"
edition = "2024"
rust-version = "1.92"

[dependencies]
idevice = { version = "0.1.65", features = [
  "core_device_proxy",
  "remote_pairing",
  "rsd",
  "tunnel_tcp_stack",
  "usbmuxd",
] }
tokio = { version = "1.53", features = ["rt-multi-thread", "macros", "net", "time"] }
